FROM registry.access.redhat.com/jboss-datavirt-6/datavirt64-openshift

LABEL Name="Hotel Booking Demo" \
   Version="latest"

#COPY files /extensions/
#COPY modules /extensions/modules/
COPY install.sh /extensions/
COPY install.properties /extensions/
